[workspace]
authors = ["Jonathan (ShueYi) To <toshuyi@gmail.com>"]
channels = ["conda-forge"]
name = "jonathanto99"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.6,<3.15"
polars = ">=1.43.2,<2"
plotnine = ">=0.15.8,<0.16"
numpy = ">=2.5.2,<3"

[pypi-dependencies]
slint = ">=1.17.1b2, <2"
